import Head from "next/head";
import React from "react";
import { IMAGES_URL } from "../../utils/constants";
import Footer from "./footer";
import Navbar from "./navbar";

interface MyProps {}

const Layout = (props: React.PropsWithChildren<MyProps>) => {
  return (
    <>
      <Head>
        <title>Le Banyan De PEC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={IMAGES_URL.favicon} />
      </Head>
      <Navbar />
      {props.children}

      <Footer />
    </>
  );
};

export default Layout;
